apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: default
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 50Mi
  accessModes:
    - ReadWriteOnce
