apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-persistentvolume
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Delete
  storageClassName: "standard"
  hostPath:
    path: "/mnt/mongo_data"
