version: "3.1"

services:
  backend:
    ## build: You can use this attribute to build the docker image for the applicaton
    image: mehdox/mongodbbackend:1.0.0
    ports:
      - 5000:5000
    env_file:
      - .env
  mongo-db:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_DB_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_DB_PASWORD}
    env_file:
      - .env
    networks:
      - mongo-db-networks
    restart: always

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_DB_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_DB_PASWORD}
      - ME_CONFIG_MONGODB_SERVER=mongo-db
    env_file:
      - .env
    depends_on:
      - "mongo-db"
    networks:
      - mongo-db-networks

networks:
  mongo-db-networks:
    driver: bridge
